version: '2.1'

services:
    rt1:
        command: "tcpdump -nSt icmp"
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
    rt2:
        command: ["ping", "-s", "4000", "rt1"]
        depends_on:
            - rt1
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
    rt3:
        command: ["ping", "rt1"]
        depends_on:
            - rt1
        sysctls:
            - net.ipv4.icmp_echo_ignore_all=1
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
    rt4:
        command: ["ping", "-c", "1", "rt3"]
        depends_on:
            - rt3
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
    tn1:
        command: "bash -c 'echo \"- interfetele de retea:\" && ip addr && echo \"- gateway:\" && ip route show'"
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet1
networks:
    tnet1: 
        ipam:
            driver: default
            config:
                - gateway: 192.192.0.1
                  subnet: 192.192.0.1/30
    tnet2:
        ipam:
            driver: default
            config:
                - gateway: 1.2.3.4
                  subnet: 1.2.3.4/24
